name: Lint and Test 

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint 
      run:  npm i && npm run lint
  run-tests:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests 
        run: npm i && npm run test